project:
  type: website
  output-dir: docs

website:
  title: "isaac_miller_website"
  navbar:
    title: "Isaac Miller"
    logo: images/Logo maker project (1).png
    logo-alt: "My Personal Logo"
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - Projects.qmd
      - resume_cv.qmd
      - relevant_coursework.qmd
      - text: "My Certifications"
        menu:
          - scuba.qmd
  page-footer:
    background: light
    left: Copyright 2026, Isaac Miller
    right: Howzit!


format:
  html:
    theme: 
    - styles.scss
    - yeti
    css: styles.css
    toc: true
    page-layout: full
    lightbox: true

editor: visual

